config/routes.rb
Rails.application.routes.draw do
  api_version(module: "V1", path: {value: "v1"}, default: true) do
    root 'links#new'
    resources :links
  end
  get '/:id' => "shortened_urls#show", as: :shortened_url

end

app/models/link.rb
class Link < ActiveRecord::Base
	has_shortened_urls
	validates :title, :original_url, :ip, presence: true
end

app/models/short_url_tracking.rb
class ShortUrlTracking < ActiveRecord::Base
	scope :short_url, -> (shortened_url_id) { where(shortened_url_id: shortened_url_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < Shortener::ShortenedUrlsController
	def show
		token = ::Shortener::ShortenedUrl.extract_token(params[:id])
	  track = Shortener.ignore_robots.blank? || request.human?
	  url   = ::Shortener::ShortenedUrl.fetch_with_token(token: token, additional_params: params, track: track)
	  redirect_to url[:url], status: :moved_permanently
	  short_url_track = ShortUrlTracking.create(shortened_url_id: url[:shortened_url][:id], client_ip: request.remote_ip)
	end
end

app/controllers/v1/base_controller.rb
class V1::BaseController < ApplicationController
end

app/controllers/v1/links_controller.rb
class V1::LinksController < V1::BaseController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.all
    respond_to do |format|
      format.html
      format.json { render json: @links }
    end    
  end

  def show
    @shortened_url = @link.shortened_urls.first
    @short_url_trackings = ShortUrlTracking.short_url(@shortened_url.id)
  end

  def new
    @link = Link.new
  end

  def edit
  end

  def create
    @link = Link.new(link_params.merge({ip: request.remote_ip}))
    respond_to do |format|
      if @link.valid?
        Link.transaction do
          @link.save
          @shortened_url = @link.shortened_urls.generate(@link.original_url)  
        end
        format.html { redirect_to default_links_path, notice: 'Link was successfully created.' }
        format.json { render json: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to v1_links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.fetch(:link, {}).permit(:original_url, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortUrlGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/v1/links/_form.html.erb
<div>
<br><br>
 <%= form_for @link, url: v1_links_path, method: "POST" do |f| %>
     <div class="form-group row">
        <label class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">URL</label>
        <div class="col-sm-10">
          <%= f.text_field :original_url, class: "form-control", placeholder: "Enter complete url with http/https" %>
        </div>
      </div>
      <%= f.hidden_field :ip, value: request.remote_ip %>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
          <%= f.submit "Submit",class: "btn btn-primary" %>
        </div>
      </div>
  <% end %>
</div>

app/views/v1/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/v1/links/index.html.erb
<div class="container">
<div>
  <h1>Dashboard</h1>
  <%= link_to 'Manage Tracked Links', new_default_link_path, class: "btn btn-primary pull-right" %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Destination Link</th>
      <th>IP</th>
      <th>Hits</th>
      <th>Tracked Link</th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <th scope="row"><%= link_to "#{link.title}", default_link_path(link) %></th>
        <th><%= link.original_url %></th>
        <td><%= link.ip %></td>
        <% short_link = link.shortened_urls.first%>
        <td><%= short_link.use_count %></td>
        <td><%= link_to "#{short_link.unique_key}", shortened_url_path(id: short_link.unique_key)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/v1/links/new.html.erb
<div class="container">
	<div>	
		<h1>New Link</h1>
		<%= link_to 'Dashboard', v1_links_path, class: "btn btn-primary pull-right" %>
	</div>
	<%= render 'form' %>
</div>

app/views/v1/links/show.html.erb
<div class="container">
	<div>
	  <h1>Link Detail</h1>
	  <%= link_to 'Dashboard', default_links_path, class: "btn btn-primary pull-right" %>
	</div>

	Title: <%= @link.title %><br>
	Original URL: <a href="<%=@link.original_url%>"><%= @link.original_url %></a><br>
	<% short_link = @link.shortened_urls.first%>
	Total Hits: <%= short_link.use_count %><br>
	Tracked URL: <%= link_to "#{short_link.unique_key}", shortened_url_path(id: short_link.unique_key) %>

	<h1>IP Visits</h1>

	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>#</th>
	      <th>IP</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @short_url_trackings.each_with_index do |track, i| %>
		    <tr>
		      <th scope="row"><%= i+1 %></th>
		      <th><%= track.client_ip %></th>
		  <%end%>
	  </tbody>
	</table>

</div>